import { Link } from 'react-router-dom'
import { Minus, Plus, ArrowRight, ShoppingBag } from 'lucide-react'
import ProductVisual from '../components/ProductVisual'

export default function CartPage({items,changeQty,removeItem}){
 const subtotal=items.reduce((s,i)=>s+i.price*i.qty,0)
 if(!items.length) return <section className="section-wrap empty-page"><ShoppingBag/><h1>Your cart is empty.</h1><p>Your next upgrade is probably a few clicks away.</p><Link className="btn primary" to="/shop">Shop tech</Link></section>
 return <section className="section-wrap cart-page"><span className="eyebrow yellow">YOUR CART</span><h1>Review your setup.</h1><div className="cart-page-grid"><div className="cart-lines">{items.map(item=><article key={item.id} className="cart-line"><div className="cart-page-thumb"><ProductVisual type={item.visual} accent={item.accent} image={item.image} alt={item.name} compact/></div><div><span>{item.brand}</span><h3>{item.name}</h3><small>{item.color}</small><div className="qty-row"><div className="qty"><button onClick={()=>changeQty(item.id,-1)}><Minus/></button><span>{item.qty}</span><button onClick={()=>changeQty(item.id,1)}><Plus/></button></div><button className="remove" onClick={()=>removeItem(item.id)}>Remove</button></div></div><strong>GH₵ {(item.price*item.qty).toLocaleString()}</strong></article>)}</div><aside className="order-summary"><span className="eyebrow">ORDER SUMMARY</span><div><span>Subtotal</span><strong>GH₵ {subtotal.toLocaleString()}</strong></div><div><span>Delivery</span><span>Calculated at checkout</span></div><hr/><div className="grand"><span>Total</span><strong>GH₵ {subtotal.toLocaleString()}</strong></div><Link className="btn primary full" to="/checkout">Continue to checkout <ArrowRight/></Link><Link className="text-link centered" to="/shop">Keep shopping</Link></aside></div></section>
}
