import { Link } from 'react-router-dom'
import { LockKeyhole, ArrowRight, UserRound } from 'lucide-react'
import ProductVisual from '../components/ProductVisual'

export default function Checkout({items,user}){
 const subtotal=items.reduce((s,i)=>s+i.price*i.qty,0)
 const delivery=items.length?60:0
 const total=subtotal+delivery
 if(!items.length) return <section className="section-wrap empty-page"><h1>No items to check out.</h1><Link className="btn primary" to="/shop">Return to shop</Link></section>
 return <section className="checkout-page section-wrap"><div className="checkout-head"><div><span className="eyebrow yellow">SECURE CHECKOUT</span><h1>Finish your order.</h1></div><span><LockKeyhole/> Payment-ready checkout</span></div><div className="checkout-grid"><form className="checkout-form" onSubmit={e=>e.preventDefault()}><section><h3>Customer</h3>{user?<div className="payment-placeholder"><UserRound/><div><strong>Signed in as {user.email}</strong><p>Your cart is synced securely to your PLUGIFY account.</p></div></div>:<div className="payment-placeholder"><UserRound/><div><strong>Continue with your PLUGIFY account</strong><p>Sign in so your cart and future orders stay attached to you.</p><Link className="text-link" to="/account">Sign in or create account →</Link></div></div>}</section><section><h3>Delivery address</h3><div className="form-grid"><label className="span-2">Street / area<input required/></label><label>City<input required placeholder="Accra"/></label><label>Region<input required/></label><label className="span-2">Phone number<input required placeholder="+233"/></label><label className="span-2">Delivery note<input placeholder="Landmark, gate instructions, etc."/></label></div></section><section><h3>Payment</h3><div className="payment-placeholder"><LockKeyhole/><div><strong>Paystack integration is next</strong><p>Your cart and customer system are live. Payment will be enabled here without changing the shopping flow.</p></div></div></section><button className="btn primary full" type="button" disabled style={{opacity:.55,cursor:'not-allowed'}}>Payment coming soon <ArrowRight/></button></form><aside className="checkout-summary"><h3>Your order</h3>{items.map(i=><div className="checkout-item" key={i.id}><div className="checkout-thumb"><ProductVisual type={i.visual} accent={i.accent} image={i.image} alt={i.name} compact/><span>{i.qty}</span></div><div><strong>{i.name}</strong><small>{i.brand}</small></div><b>GH₵ {(i.price*i.qty).toLocaleString()}</b></div>)}<hr/><div><span>Subtotal</span><strong>GH₵ {subtotal.toLocaleString()}</strong></div><div><span>Delivery</span><strong>GH₵ {delivery.toLocaleString()}</strong></div><div className="grand"><span>Total</span><strong>GH₵ {total.toLocaleString()}</strong></div></aside></div></section>
}
